mkdir -p C
cd C
git clone https://github.com/torvalds/linux.git
git clone https://github.com/antirez/redis.git
git clone https://github.com/firehol/netdata.git
git clone https://github.com/git/git.git
git clone https://github.com/SamyPesse/How-to-Make-a-Computer-Operating-System.git
git clone https://github.com/Bilibili/ijkplayer.git
git clone https://github.com/kripken/emscripten.git
git clone https://github.com/ggreer/the_silver_searcher.git
git clone https://github.com/php/php-src.git
git clone https://github.com/wg/wrk.git
git clone https://github.com/julycoding/The-Art-Of-Programming-By-July.git
git clone https://github.com/grpc/grpc.git
git clone https://github.com/vim/vim.git
git clone https://github.com/stedolan/jq.git
git clone https://github.com/irungentoo/toxcore.git
git clone https://github.com/WhisperSystems/Signal-Android.git
git clone https://github.com/DrKLO/Telegram.git
git clone https://github.com/twitter/twemproxy.git
git clone https://github.com/torch/torch7.git
git clone https://github.com/arduino/Arduino.git
git clone https://github.com/FFmpeg/FFmpeg.git
git clone https://github.com/h2o/h2o.git
git clone https://github.com/tmux/tmux.git
git clone https://github.com/vurtun/nuklear.git
git clone https://github.com/antirez/disque.git
git clone https://github.com/libgit2/libgit2.git
git clone https://github.com/robertdavidgraham/masscan.git
git clone https://github.com/memcached/memcached.git
git clone https://github.com/libuv/libuv.git
git clone https://github.com/googlecreativelab/anypixel.git
git clone https://github.com/octalmage/robotjs.git
git clone https://github.com/liuliu/ccv.git
git clone https://github.com/jp9000/obs-studio.git
git clone https://github.com/swoole/swoole-src.git
git clone https://github.com/b4winckler/macvim.git
git clone https://github.com/alibaba/tengine.git
git clone https://github.com/mpv-player/mpv.git
git clone https://github.com/commaai/openpilot.git
git clone https://github.com/nothings/stb.git
git clone https://github.com/sdegutis/mjolnir.git
git clone https://github.com/allinurl/goaccess.git
git clone https://github.com/cloudwu/skynet.git
git clone https://github.com/facebook/zstd.git
git clone https://github.com/phpredis/phpredis.git
git clone https://github.com/haiwen/seafile.git
git clone https://github.com/arut/nginx-rtmp-module.git
git clone https://github.com/curl/curl.git
git clone https://github.com/micropython/micropython.git
git clone https://github.com/google/brotli.git
git clone https://github.com/symless/synergy.git
git clone https://github.com/openssl/openssl.git
git clone https://github.com/fogleman/Craft.git
git clone https://github.com/mist64/xhyve.git
git clone https://github.com/openresty/lua-nginx-module.git
git clone https://github.com/jgamblin/Mirai-Source-Code.git
git clone https://github.com/radare/radare2.git
git clone https://github.com/andlabs/libui.git
git clone https://github.com/jonas/tig.git
git clone https://github.com/matz/streem.git
git clone https://github.com/coolwanglu/vim.js.git
git clone https://github.com/numpy/numpy.git
git clone https://github.com/lpereira/lwan.git
git clone https://github.com/jedisct1/libsodium.git
git clone https://github.com/vmg/redcarpet.git
git clone https://github.com/kr/beanstalkd.git
git clone https://github.com/mruby/mruby.git
git clone https://github.com/rswier/c4.git
git clone https://github.com/raspberrypi/linux.git
git clone https://github.com/cesanta/mongoose.git
git clone https://github.com/wishstudio/flinux.git
git clone https://github.com/deepmind/lab.git
git clone https://github.com/nanomsg/nanomsg.git
git clone https://github.com/squeaky-pl/japronto.git
git clone https://github.com/joyent/libuv.git
git clone https://github.com/SoftEtherVPN/SoftEtherVPN.git
git clone https://github.com/fastos/fastsocket.git
git clone https://github.com/Xfennec/progress.git
git clone https://github.com/gentilkiwi/mimikatz.git
git clone https://github.com/nodemcu/nodemcu-firmware.git
git clone https://github.com/nodejs/http-parser.git
git clone https://github.com/openresty/openresty.git
git clone https://github.com/orangeduck/Cello.git
git clone https://github.com/antirez/kilo.git
git clone https://github.com/nginx/nginx.git
git clone https://github.com/bartobri/no-more-secrets.git
git clone https://github.com/cinder/Cinder.git
git clone https://github.com/vysheng/tg.git
git clone https://github.com/fulldecent/system-bus-radio.git
git clone https://github.com/laruence/yaf.git
git clone https://github.com/philipl/pifs.git
git clone https://github.com/macvim-dev/macvim.git
git clone https://github.com/awslabs/s2n.git
git clone https://github.com/rui314/8cc.git
git clone https://github.com/pbatard/rufus.git
git clone https://github.com/gali8/Tesseract-OCR-iOS.git
git clone https://github.com/mofarrell/p2pvc.git
git clone https://github.com/PowerShell/Win32-OpenSSH.git
git clone https://github.com/visit1985/mdp.git
git clone https://github.com/postgres/postgres.git
git clone https://github.com/freebsd/freebsd.git
