mkdir -p Clojure
cd Clojure
git clone https://github.com/tonsky/FiraCode.git
git clone https://github.com/LightTable/LightTable.git
git clone https://github.com/clojure/clojurescript.git
git clone https://github.com/omcljs/om.git
git clone https://github.com/technomancy/leiningen.git
git clone https://github.com/overtone/overtone.git
git clone https://github.com/riemann/riemann.git
git clone https://github.com/weavejester/compojure.git
git clone https://github.com/frankiesardo/icepick.git
git clone https://github.com/functional-koans/clojure-koans.git
git clone https://github.com/alda-lang/alda.git
git clone https://github.com/tonsky/datascript.git
git clone https://github.com/swannodette/mori.git
git clone https://github.com/reagent-project/reagent.git
git clone https://github.com/Day8/re-frame.git
git clone https://github.com/magomimmo/modern-cljs.git
git clone https://github.com/jepsen-io/jepsen.git
git clone https://github.com/ring-clojure/ring.git
git clone https://github.com/bhauman/lein-figwheel.git
git clone https://github.com/incanter/incanter.git
git clone https://github.com/quil/quil.git
git clone https://github.com/ztellman/aleph.git
git clone https://github.com/clojure-cookbook/clojure-cookbook.git
git clone https://github.com/Engelberg/instaparse.git
git clone https://github.com/plumatic/schema.git
git clone https://github.com/pedestal/pedestal.git
git clone https://github.com/weavejester/hiccup.git
git clone https://github.com/cognitect/transit-format.git
git clone https://github.com/onyx-platform/onyx.git
git clone https://github.com/nathanmarz/specter.git
git clone https://github.com/cgrand/enlive.git
git clone https://github.com/stuartsierra/component.git
git clone https://github.com/clojure/core.async.git
git clone https://github.com/nathanmarz/cascalog.git
git clone https://github.com/marick/Midje.git
git clone https://github.com/plumatic/plumbing.git
git clone https://github.com/frankiesardo/auto-parcel.git
git clone https://github.com/korma/Korma.git
git clone https://github.com/wit-ai/duckling.git
git clone https://github.com/boot-clj/boot.git
git clone https://github.com/Factual/drake.git
git clone https://github.com/ptaoussanis/sente.git
git clone https://github.com/krisajenkins/yesql.git
git clone https://github.com/jonase/kibit.git
git clone https://github.com/daveray/seesaw.git
git clone https://github.com/cemerick/friend.git
git clone https://github.com/clojure-liberator/liberator.git
git clone https://github.com/shaunlebron/parinfer.git
git clone https://github.com/oakes/Nightcode.git
git clone https://github.com/bhauman/devcards.git
git clone https://github.com/dakrone/clj-http.git
git clone https://github.com/plexus/chestnut.git
git clone https://github.com/clojure/core.logic.git
git clone https://github.com/noprompt/frak.git
git clone https://github.com/viebel/klipse.git
git clone https://github.com/ptaoussanis/timbre.git
git clone https://github.com/clojure/core.typed.git
git clone https://github.com/emezeske/lein-cljsbuild.git
git clone https://github.com/dakrone/cheshire.git
git clone https://github.com/venantius/ultra.git
git clone https://github.com/oakes/play-clj.git
git clone https://github.com/arcadia-unity/Arcadia.git
git clone https://github.com/dvcrn/markright.git
git clone https://github.com/swannodette/lt-cljs-tutorial.git
git clone https://github.com/schani/clojurec.git
git clone https://github.com/swannodette/logic-tutorial.git
git clone https://github.com/4clojure/4clojure.git
git clone https://github.com/circleci/frontend.git
git clone https://github.com/noir-clojure/noir.git
git clone https://github.com/datacrypt-project/hitchhiker-tree.git
git clone https://github.com/pallet/pallet.git
git clone https://github.com/noprompt/garden.git
git clone https://github.com/hugoduncan/criterium.git
git clone https://github.com/clojure/core.match.git
git clone https://github.com/puniverse/pulsar.git
git clone https://github.com/ztellman/lamina.git
git clone https://github.com/clojure/test.check.git
git clone https://github.com/plumatic/dommy.git
git clone https://github.com/hoplon/hoplon.git
git clone https://github.com/ptaoussanis/carmine.git
git clone https://github.com/LuxLang/lux.git
git clone https://github.com/binaryage/cljs-devtools.git
git clone https://github.com/juxt/bidi.git
git clone https://github.com/metosin/compojure-api.git
git clone https://github.com/adamtornhill/code-maat.git
git clone https://github.com/gf3/secretary.git
git clone https://github.com/anmonteiro/lumo.git
git clone https://github.com/clojure-android/lein-droid.git
git clone https://github.com/weavejester/environ.git
git clone https://github.com/dakrone/clojure-opennlp.git
git clone https://github.com/jonase/eastwood.git
git clone https://github.com/oakes/Nightlight.git
git clone https://github.com/aphyr/tesser.git
git clone https://github.com/mcohen01/amazonica.git
git clone https://github.com/pkamenarsky/atea.git
git clone https://github.com/asciinema/asciinema-player.git
git clone https://github.com/levand/quiescent.git
git clone https://github.com/hoplon/javelin.git
git clone https://github.com/tolitius/mount.git
git clone https://github.com/puppetlabs/trapperkeeper.git
