mkdir -p CoffeeScript
cd CoffeeScript
git clone https://github.com/atom/atom.git
git clone https://github.com/jashkenas/coffeescript.git
git clone https://github.com/github/hubot.git
git clone https://github.com/postcss/autoprefixer.git
git clone https://github.com/enyo/dropzone.git
git clone https://github.com/basecamp/trix.git
git clone https://github.com/dropbox/zxcvbn.git
git clone https://github.com/philc/vimium.git
git clone https://github.com/morrisjs/morris.js.git
git clone https://github.com/michaelvillar/dynamics.js.git
git clone https://github.com/FelisCatus/SwitchyOmega.git
git clone https://github.com/baconjs/bacon.js.git
git clone https://github.com/yhatt/marp.git
git clone https://github.com/codecombat/codecombat.git
git clone https://github.com/ichord/At.js.git
git clone https://github.com/riccardoscalco/textures.git
git clone https://github.com/sharelatex/sharelatex.git
git clone https://github.com/sorich87/bootstrap-tour.git
git clone https://github.com/stripe/jquery.payment.git
git clone https://github.com/turbolinks/turbolinks-classic.git
git clone https://github.com/gka/chroma.js.git
git clone https://github.com/github/hubot-scripts.git
git clone https://github.com/basecamp/pow.git
git clone https://github.com/JoelBesada/activate-power-mode.git
git clone https://github.com/NarrativeScience/Log.io.git
git clone https://github.com/turbolinks/turbolinks.git
git clone https://github.com/jnordberg/wintersmith.git
git clone https://github.com/dmauro/Keypress.git
git clone https://github.com/chaplinjs/chaplin.git
git clone https://github.com/devongovett/pdfkit.git
git clone https://github.com/docpad/docpad.git
git clone https://github.com/danielgtaylor/aglio.git
git clone https://github.com/Morhaus/dispatch-proxy.git
git clone https://github.com/yakyak/yakyak.git
git clone https://github.com/angular-ui/angular-google-maps.git
git clone https://github.com/sparanoid/chinese-copywriting-guidelines.git
git clone https://github.com/bergie/hallo.git
git clone https://github.com/taigaio/taiga-front.git
git clone https://github.com/jianliaoim/talk-os.git
git clone https://github.com/Leonidas-from-XIV/node-xml2js.git
git clone https://github.com/dmotz/oriDomi.git
git clone https://github.com/nicolaskruchten/pivottable.git
git clone https://github.com/jakubroztocil/cloudtunes.git
git clone https://github.com/leafo/sticky-kit.git
git clone https://github.com/noflo/noflo.git
git clone https://github.com/soyjavi/QuoJS.git
git clone https://github.com/paradoxxxzero/butterfly.git
git clone https://github.com/js2coffee/js2coffee.git
git clone https://github.com/stevenschobert/instafeed.js.git
git clone https://github.com/michaelficarra/CoffeeScriptRedux.git
git clone https://github.com/lynndylanhurley/ng-token-auth.git
git clone https://github.com/slackapi/hubot-slack.git
git clone https://github.com/sstephenson/eco.git
git clone https://github.com/atom/vim-mode.git
git clone https://github.com/batmanjs/batman.git
git clone https://github.com/McPants/jquery.shapeshift.git
git clone https://github.com/HubSpot/BuckyClient.git
git clone https://github.com/shadowsocks/shadowsocks-gui.git
git clone https://github.com/tomdionysus/foaas.git
git clone https://github.com/apiaryio/dredd.git
git clone https://github.com/oauth-io/oauthd.git
git clone https://github.com/ai/visibilityjs.git
git clone https://github.com/jescalan/roots.git
git clone https://github.com/serkanyersen/ifvisible.js.git
git clone https://github.com/Pathgather/please-wait.git
git clone https://github.com/dropbox/dropbox-js.git
git clone https://github.com/sockjs/sockjs-node.git
git clone https://github.com/okTurtles/dnschain.git
git clone https://github.com/ExpediaInceCommercePlatform/cyclotron.git
git clone https://github.com/osscafe/gulp-cheatsheet.git
git clone https://github.com/mauricemach/coffeekup.git
git clone https://github.com/rpominov/kefir.git
git clone https://github.com/linemanjs/lineman.git
git clone https://github.com/artursapek/mondrian.git
git clone https://github.com/replit/repl.it.git
git clone https://github.com/easelinc/tourist.git
git clone https://github.com/akhodakivskiy/VimFx.git
git clone https://github.com/sgentle/caniuse-cmd.git
git clone https://github.com/basecamp/local_time.git
git clone https://github.com/oskarkrawczyk/Heyoffline.git
git clone https://github.com/passy/angular-masonry.git
git clone https://github.com/sstephenson/stitch.git
git clone https://github.com/bucketsio/buckets.git
git clone https://github.com/leeluolee/puer.git
git clone https://github.com/jaymedavis/hubble.git
git clone https://github.com/groupon/greenscreen.git
git clone https://github.com/kossnocorp/jquery.turbolinks.git
git clone https://github.com/soulwire/Coffee-Physics.git
git clone https://github.com/littlebee/git-time-machine.git
git clone https://github.com/sinker/tacofancy.git
git clone https://github.com/hiddentao/squel.git
git clone https://github.com/mauricemach/zappa.git
git clone https://github.com/bevry/cson.git
git clone https://github.com/shadowsocks/shadowsocks-nodejs.git
git clone https://github.com/domenic/chai-as-promised.git
git clone https://github.com/atmos/camo.git
git clone https://github.com/rs/pushd.git
git clone https://github.com/audiocogs/aurora.js.git
git clone https://github.com/thingdom/node-neo4j.git
git clone https://github.com/atom/apm.git
