mkdir -p Cpp
cd Cpp
git clone https://github.com/tensorflow/tensorflow.git
git clone https://github.com/electron/electron.git
git clone https://github.com/apple/swift.git
git clone https://github.com/nwjs/nw.js.git
git clone https://github.com/rethinkdb/rethinkdb.git
git clone https://github.com/BVLC/caffe.git
git clone https://github.com/google/protobuf.git
git clone https://github.com/facebook/hhvm.git
git clone https://github.com/opencv/opencv.git
git clone https://github.com/bitcoin/bitcoin.git
git clone https://github.com/mongodb/mongo.git
git clone https://github.com/Microsoft/CNTK.git
git clone https://github.com/cocos2d/cocos2d-x.git
git clone https://github.com/tesseract-ocr/tesseract.git
git clone https://github.com/google/leveldb.git
git clone https://github.com/facebookresearch/fastText.git
git clone https://github.com/facebook/folly.git
git clone https://github.com/Tencent/mars.git
git clone https://github.com/facebook/osquery.git
git clone https://github.com/godotengine/godot.git
git clone https://github.com/google/flatbuffers.git
git clone https://github.com/facebook/rocksdb.git
git clone https://github.com/CRYTEK-CRYENGINE/CRYENGINE.git
git clone https://github.com/uWebSockets/uWebSockets.git
git clone https://github.com/dmlc/xgboost.git
git clone https://github.com/mobile-shell/mosh.git
git clone https://github.com/ocornut/imgui.git
git clone https://github.com/yangyangwithgnu/hardseed.git
git clone https://github.com/xbmc/xbmc.git
git clone https://github.com/SFTtech/openage.git
git clone https://github.com/sqlitebrowser/sqlitebrowser.git
git clone https://github.com/haoel/leetcode.git
git clone https://github.com/facebook/watchman.git
git clone https://github.com/paralect/robomongo.git
git clone https://github.com/wkhtmltopdf/wkhtmltopdf.git
git clone https://github.com/alibaba/AndFix.git
git clone https://github.com/openframeworks/openFrameworks.git
git clone https://github.com/paulasmuth/fnordmetric.git
git clone https://github.com/nlohmann/json.git
git clone https://github.com/googlei18n/libphonenumber.git
git clone https://github.com/telegramdesktop/tdesktop.git
git clone https://github.com/v8/v8.git
git clone https://github.com/zealdocs/zeal.git
git clone https://github.com/facebook/proxygen.git
git clone https://github.com/aria2/aria2.git
git clone https://github.com/esp8266/Arduino.git
git clone https://github.com/PaddlePaddle/Paddle.git
git clone https://github.com/google/googletest.git
git clone https://github.com/philsquared/Catch.git
git clone https://github.com/bjorn/tiled.git
git clone https://github.com/sandstorm-io/capnproto.git
git clone https://github.com/uglide/RedisDesktopManager.git
git clone https://github.com/draios/sysdig.git
git clone https://github.com/ideawu/ssdb.git
git clone https://github.com/miloyip/rapidjson.git
git clone https://github.com/openalpr/openalpr.git
git clone https://github.com/dropbox/lepton.git
git clone https://github.com/Automattic/node-canvas.git
git clone https://github.com/notepad-plus-plus/notepad-plus-plus.git
git clone https://github.com/ssloy/tinyrenderer.git
git clone https://github.com/acaudwell/Gource.git
git clone https://github.com/phusion/passenger.git
git clone https://github.com/TrinityCore/TrinityCore.git
git clone https://github.com/amznlabs/amazon-dsstne.git
git clone https://github.com/TTimo/doom3.gpl.git
git clone https://github.com/sass/node-sass.git
git clone https://github.com/visualfc/liteide.git
git clone https://github.com/facebookarchive/scribe.git
git clone https://github.com/appjs/appjs.git
git clone https://github.com/tekezo/Karabiner-Elements.git
git clone https://github.com/sass/libsass.git
git clone https://github.com/facebook/redex.git
git clone https://github.com/apache/thrift.git
git clone https://github.com/arangodb/arangodb.git
git clone https://github.com/tjanczuk/edge.git
git clone https://github.com/pagespeed/ngx_pagespeed.git
git clone https://github.com/SFML/SFML.git
git clone https://github.com/Maximus5/ConEmu.git
git clone https://github.com/zeromq/libzmq.git
git clone https://github.com/tekezo/Karabiner.git
git clone https://github.com/audiokit/AudioKit.git
git clone https://github.com/keepassx/keepassx.git
git clone https://github.com/dolphin-emu/dolphin.git
git clone https://github.com/koekeishiya/kwm.git
git clone https://github.com/kyleneideck/BackgroundMusic.git
git clone https://github.com/webscalesql/webscalesql-5.6.git
git clone https://github.com/google/lmctfy.git
git clone https://github.com/chenshuo/muduo.git
git clone https://github.com/ceph/ceph.git
git clone https://github.com/ipkn/crow.git
git clone https://github.com/apache/mesos.git
git clone https://github.com/googlesamples/android-ndk.git
git clone https://github.com/citra-emu/citra.git
git clone https://github.com/bkaradzic/bgfx.git
git clone https://github.com/scylladb/scylla.git
git clone https://github.com/hrydgard/ppsspp.git
git clone https://github.com/google/liquidfun.git
git clone https://github.com/jasarien/Provenance.git
git clone https://github.com/breach/thrust.git
git clone https://github.com/Squirrel/Squirrel.Windows.git
