mkdir -p CSharp
cd CSharp
git clone https://github.com/dotnet/corefx.git
git clone https://github.com/shadowsocks/shadowsocks-windows.git
git clone https://github.com/thedillonb/CodeHub.git
git clone https://github.com/dotnet/coreclr.git
git clone https://github.com/dotnet/roslyn.git
git clone https://github.com/mxgmn/WaveFunctionCollapse.git
git clone https://github.com/PowerShell/PowerShell.git
git clone https://github.com/SignalR/SignalR.git
git clone https://github.com/StackExchange/Dapper.git
git clone https://github.com/mono/mono.git
git clone https://github.com/ShareX/ShareX.git
git clone https://github.com/NancyFx/Nancy.git
git clone https://github.com/Wox-launcher/Wox.git
git clone https://github.com/aspnet/EntityFramework.git
git clone https://github.com/AutoMapper/AutoMapper.git
git clone https://github.com/MonoGame/MonoGame.git
git clone https://github.com/restsharp/RestSharp.git
git clone https://github.com/aspnet/Mvc.git
git clone https://github.com/JamesNK/Newtonsoft.Json.git
git clone https://github.com/OpenRA/OpenRA.git
git clone https://github.com/hbons/SparkleShare.git
git clone https://github.com/ServiceStack/ServiceStack.git
git clone https://github.com/Microsoft/BotBuilder.git
git clone https://github.com/Redth/PushSharp.git
git clone https://github.com/icsharpcode/ILSpy.git
git clone https://github.com/MahApps/MahApps.Metro.git
git clone https://github.com/brandonlw/Psychson.git
git clone https://github.com/Microsoft/msbuild.git
git clone https://github.com/reactiveui/ReactiveUI.git
git clone https://github.com/opserver/Opserver.git
git clone https://github.com/cefsharp/CefSharp.git
git clone https://github.com/chocolatey/choco.git
git clone https://github.com/HearthSim/Hearthstone-Deck-Tracker.git
git clone https://github.com/dotnet/orleans.git
git clone https://github.com/ResourceHunter/BaiduPanDownloadWinform.git
git clone https://github.com/01org/acat.git
git clone https://github.com/OptiKey/OptiKey.git
git clone https://github.com/ButchersBoy/MaterialDesignInXamlToolkit.git
git clone https://github.com/Humanizr/Humanizer.git
git clone https://github.com/aspnetboilerplate/aspnetboilerplate.git
git clone https://github.com/HangfireIO/Hangfire.git
git clone https://github.com/Microsoft/GVFS.git
git clone https://github.com/KeenSoftwareHouse/SpaceEngineers.git
git clone https://github.com/jaredpar/VsVim.git
git clone https://github.com/NLog/NLog.git
git clone https://github.com/Sonarr/Sonarr.git
git clone https://github.com/akkadotnet/akka.net.git
git clone https://github.com/App-vNext/Polly.git
git clone https://github.com/AvaloniaUI/Avalonia.git
git clone https://github.com/JeremySkinner/FluentValidation.git
git clone https://github.com/gitextensions/gitextensions.git
git clone https://github.com/Nummer/Destroy-Windows-10-Spying.git
git clone https://github.com/StackExchange/StackExchange.Redis.git
git clone https://github.com/OpenLiveWriter/OpenLiveWriter.git
git clone https://github.com/Glimpse/Glimpse.git
git clone https://github.com/EventStore/EventStore.git
git clone https://github.com/dotnet/cli.git
git clone https://github.com/MvvmCross/MvvmCross.git
git clone https://github.com/IdentityServer/IdentityServer3.git
git clone https://github.com/mono/monodevelop.git
git clone https://github.com/Topshelf/Topshelf.git
git clone https://github.com/dotnet/BenchmarkDotNet.git
git clone https://github.com/Microsoft/react-native-windows.git
git clone https://github.com/JeffreySu/WeiXinMPSDK.git
git clone https://github.com/scriptcs/scriptcs.git
git clone https://github.com/Reactive-Extensions/Rx.NET.git
git clone https://github.com/aspnet/JavaScriptServices.git
git clone https://github.com/quartznet/quartznet.git
git clone https://github.com/ninject/Ninject.git
git clone https://github.com/0xd4d/dnSpy.git
git clone https://github.com/moq/moq4.git
git clone https://github.com/thangchung/awesome-dotnet-core.git
git clone https://github.com/googlevr/gvr-unity-sdk.git
git clone https://github.com/ravendb/ravendb.git
git clone https://github.com/accord-net/framework.git
git clone https://github.com/FransBouma/Massive.git
git clone https://github.com/playgameservices/play-games-plugin-for-unity.git
git clone https://github.com/projectkudu/kudu.git
git clone https://github.com/JimBobSquarePants/ImageProcessor.git
git clone https://github.com/rabbitmq/rabbitmq-tutorials.git
git clone https://github.com/SonyWWS/ATF.git
git clone https://github.com/Microsoft/PTVS.git
git clone https://github.com/domaindrivendev/Swashbuckle.git
git clone https://github.com/mongodb/mongo-csharp-driver.git
git clone https://github.com/SiliconStudio/xenko.git
git clone https://github.com/umbraco/Umbraco-CMS.git
git clone https://github.com/dotnet-state-machine/stateless.git
git clone https://github.com/TheBerkin/Rant.git
git clone https://github.com/OneGet/oneget.git
git clone https://github.com/Microsoft/nodejstools.git
git clone https://github.com/xamarin/xamarin-forms-samples.git
git clone https://github.com/kevin-montrose/Jil.git
git clone https://github.com/louthy/language-ext.git
git clone https://github.com/aspnet/KestrelHttpServer.git
git clone https://github.com/xamarin/monodroid-samples.git
git clone https://github.com/0xd4d/de4dot.git
git clone https://github.com/Fody/Fody.git
git clone https://github.com/autofac/Autofac.git
git clone https://github.com/fluentmigrator/fluentmigrator.git
git clone https://github.com/akavache/Akavache.git
