mkdir -p Erlang
cd Erlang
git clone https://github.com/erlang/otp.git
git clone https://github.com/ninenines/cowboy.git
git clone https://github.com/processone/ejabberd.git
git clone https://github.com/rabbitmq/rabbitmq-server.git
git clone https://github.com/emqtt/emqttd.git
git clone https://github.com/ChicagoBoss/ChicagoBoss.git
git clone https://github.com/mochi/mochiweb.git
git clone https://github.com/rvirding/lfe.git
git clone https://github.com/discoproject/disco.git
git clone https://github.com/webmachine/webmachine.git
git clone https://github.com/processone/tsung.git
git clone https://github.com/basho/rebar.git
git clone https://github.com/synrc/n2o.git
git clone https://github.com/klacke/yaws.git
git clone https://github.com/leo-project/leofs.git
git clone https://github.com/biokoda/actordb.git
git clone https://github.com/rebar/rebar.git
git clone https://github.com/devinus/poolboy.git
git clone https://github.com/erlio/vernemq.git
git clone https://github.com/nitrogen/nitrogen.git
git clone https://github.com/erlang-lager/lager.git
git clone https://github.com/basho/riak_core.git
git clone https://github.com/heroku/logplex.git
git clone https://github.com/tarcieri/reia.git
git clone https://github.com/uwiger/gproc.git
git clone https://github.com/esl/MongooseIM.git
git clone https://github.com/ferd/recon.git
git clone https://github.com/ninenines/ranch.git
git clone https://github.com/benoitc/hackney.git
git clone https://github.com/knutin/elli.git
git clone https://github.com/ostinelli/misultin.git
git clone https://github.com/davisp/jiffy.git
git clone https://github.com/dcos/minuteman.git
git clone https://github.com/erlang/rebar3.git
git clone https://github.com/rustyio/sync.git
git clone https://github.com/boundary/folsom.git
git clone https://github.com/manopapad/proper.git
git clone https://github.com/talentdeficit/jsx.git
git clone https://github.com/rvirding/luerl.git
git clone https://github.com/eproxus/meck.git
git clone https://github.com/zotonic/zotonic.git
git clone https://github.com/wooga/eredis.git
git clone https://github.com/basho/riak_cs.git
git clone https://github.com/erlcloud/erlcloud.git
git clone https://github.com/couchbase/geocouch.git
git clone https://github.com/basho/bitcask.git
git clone https://github.com/cmullaparthi/ibrowse.git
git clone https://github.com/2600hz/kazoo.git
git clone https://github.com/erlware/relx.git
git clone https://github.com/lasp-lang/lasp.git
git clone https://github.com/hdima/erlport.git
git clone https://github.com/mojombo/ernie.git
git clone https://github.com/cbd/edis.git
git clone https://github.com/couchbaselabs/iOS-Couchbase.git
git clone https://github.com/erlydtl/erlydtl.git
git clone https://github.com/Vagabond/gen_smtp.git
git clone https://github.com/boundary/flake.git
git clone https://github.com/ericmoritz/wsdemo.git
git clone https://github.com/joxa/joxa.git
git clone https://github.com/ferd/erlang-history.git
git clone https://github.com/dalmatinerdb/dalmatinerdb.git
git clone https://github.com/massemanet/eper.git
git clone https://github.com/Feuerlabs/exometer.git
git clone https://github.com/xslogic/phoebus.git
git clone https://github.com/alpaca-lang/alpaca.git
git clone https://github.com/basho/riak_kv.git
git clone https://github.com/moonpolysoft/dynomite.git
git clone https://github.com/basho/erlang_protobuffs.git
git clone https://github.com/heroku/vegur.git
git clone https://github.com/wg/epgsql.git
git clone https://github.com/inaka/erlang_guidelines.git
git clone https://github.com/ninenines/gun.git
git clone https://github.com/yrashk/socket.io-erlang.git
git clone https://github.com/zhongwencool/observer_cli.git
git clone https://github.com/erlware/Erlang-and-OTP-in-Action-Source.git
git clone https://github.com/Asana/kraken.git
git clone https://github.com/matteoredaelli/ebot.git
git clone https://github.com/thusfresh/switchboard.git
git clone https://github.com/tjarvstrand/edts.git
git clone https://github.com/tim/erlang-oauth.git
git clone https://github.com/sky-big/RabbitMQ.git
git clone https://github.com/aweber/rabbitmq-autocluster.git
git clone https://github.com/basho/basho_bench.git
git clone https://github.com/KirinDave/fuzed.git
git clone https://github.com/zkessin/testing-erlang-book.git
git clone https://github.com/inaka/apns4erl.git
git clone https://github.com/ninenines/bullet.git
git clone https://github.com/jlouis/etorrent.git
git clone https://github.com/jlouis/fuse.git
git clone https://github.com/krestenkrab/triq.git
git clone https://github.com/basho/riak-erlang-client.git
git clone https://github.com/seancribbs/neotoma.git
git clone https://github.com/krestenkrab/hanoidb.git
git clone https://github.com/rabbitmq/erlando.git
git clone https://github.com/sinasamavati/leptus.git
git clone https://github.com/NetComposer/nksip.git
git clone https://github.com/yueyoum/make-proxy.git
git clone https://github.com/CloudI/CloudI.git
git clone https://github.com/beamspirit/bigwig.git
git clone https://github.com/andrewjstone/rafter.git
