mkdir -p Go
cd Go
git clone https://github.com/docker/docker.git
git clone https://github.com/golang/go.git
git clone https://github.com/getlantern/lantern.git
git clone https://github.com/kubernetes/kubernetes.git
git clone https://github.com/avelino/awesome-go.git
git clone https://github.com/gogits/gogs.git
git clone https://github.com/spf13/hugo.git
git clone https://github.com/syncthing/syncthing.git
git clone https://github.com/grafana/grafana.git
git clone https://github.com/astaxie/build-web-application-with-golang.git
git clone https://github.com/coreos/etcd.git
git clone https://github.com/mholt/caddy.git
git clone https://github.com/influxdata/influxdb.git
git clone https://github.com/astaxie/beego.git
git clone https://github.com/github/hub.git
git clone https://github.com/inconshreveable/ngrok.git
git clone https://github.com/gin-gonic/gin.git
git clone https://github.com/go-martini/martini.git
git clone https://github.com/cayleygraph/cayley.git
git clone https://github.com/drone/drone.git
git clone https://github.com/cockroachdb/cockroach.git
git clone https://github.com/hashicorp/consul.git
git clone https://github.com/prometheus/prometheus.git
git clone https://github.com/nsqio/nsq.git
git clone https://github.com/revel/revel.git
git clone https://github.com/junegunn/fzf.git
git clone https://github.com/joewalnes/websocketd.git
git clone https://github.com/hashicorp/terraform.git
git clone https://github.com/google/grumpy.git
git clone https://github.com/pingcap/tidb.git
git clone https://github.com/yudai/gotty.git
git clone https://github.com/buger/goreplay.git
git clone https://github.com/containous/traefik.git
git clone https://github.com/coreos/rkt.git
git clone https://github.com/labstack/echo.git
git clone https://github.com/kataras/iris.git
git clone https://github.com/hashicorp/vault.git
git clone https://github.com/mitchellh/packer.git
git clone https://github.com/go-kit/kit.git
git clone https://github.com/attic-labs/noms.git
git clone https://github.com/minio/minio.git
git clone https://github.com/flynn/flynn.git
git clone https://github.com/fogleman/primitive.git
git clone https://github.com/asciimoo/wuzz.git
git clone https://github.com/boltdb/bolt.git
git clone https://github.com/gizak/termui.git
git clone https://github.com/ncw/rclone.git
git clone https://github.com/urfave/cli.git
git clone https://github.com/CodisLabs/codis.git
git clone https://github.com/google/cadvisor.git
git clone https://github.com/jinzhu/gorm.git
git clone https://github.com/tsenart/vegeta.git
git clone https://github.com/golang/groupcache.git
git clone https://github.com/derekparker/delve.git
git clone https://github.com/cyfdecyf/cow.git
git clone https://github.com/zyedidia/micro.git
git clone https://github.com/apex/apex.git
git clone https://github.com/gopherjs/gopherjs.git
git clone https://github.com/schachmat/wego.git
git clone https://github.com/rakyll/boom.git
git clone https://github.com/xtaci/kcptun.git
git clone https://github.com/tylertreat/comcast.git
git clone https://github.com/julienschmidt/httprouter.git
git clone https://github.com/weaveworks/weave.git
git clone https://github.com/cloudson/gitql.git
git clone https://github.com/Unknwon/the-way-to-go_ZH_CN.git
git clone https://github.com/urfave/negroni.git
git clone https://github.com/git-lfs/git-lfs.git
git clone https://github.com/youtube/vitess.git
git clone https://github.com/tools/godep.git
git clone https://github.com/sirupsen/logrus.git
git clone https://github.com/docker/swarm.git
git clone https://github.com/google/seesaw.git
git clone https://github.com/valyala/fasthttp.git
git clone https://github.com/simeji/jid.git
git clone https://github.com/Masterminds/glide.git
git clone https://github.com/chrislusf/seaweedfs.git
git clone https://github.com/sosedoff/pgweb.git
git clone https://github.com/dinedal/textql.git
git clone https://github.com/hashicorp/serf.git
git clone https://github.com/andlabs/ui.git
git clone https://github.com/gravitational/teleport.git
git clone https://github.com/spf13/cobra.git
git clone https://github.com/sjwhitworth/golearn.git
git clone https://github.com/fatedier/frp.git
git clone https://github.com/PuerkitoBio/goquery.git
git clone https://github.com/docker/machine.git
git clone https://github.com/elastic/beats.git
git clone https://github.com/google/gxui.git
git clone https://github.com/future-architect/vuls.git
git clone https://github.com/schollz/find.git
git clone https://github.com/peco/peco.git
git clone https://github.com/kelseyhightower/confd.git
git clone https://github.com/nsf/gocode.git
git clone https://github.com/opencontainers/runc.git
git clone https://github.com/gorilla/mux.git
git clone https://github.com/bcicen/ctop.git
git clone https://github.com/v2ray/v2ray-core.git
git clone https://github.com/google/git-appraise.git
git clone https://github.com/eBay/fabio.git
