mkdir -p Haskell
cd Haskell
git clone https://github.com/jgm/pandoc.git
git clone https://github.com/begriffs/postgrest.git
git clone https://github.com/koalaman/shellcheck.git
git clone https://github.com/elm-lang/elm-compiler.git
git clone https://github.com/purescript/purescript.git
git clone https://github.com/facebook/Haxl.git
git clone https://github.com/commercialhaskell/stack.git
git clone https://github.com/yesodweb/yesod.git
git clone https://github.com/sdiehl/write-you-a-haskell.git
git clone https://github.com/idris-lang/Idris-dev.git
git clone https://github.com/ghcjs/ghcjs.git
git clone https://github.com/jaspervdj/hakyll.git
git clone https://github.com/gibiansky/IHaskell.git
git clone https://github.com/jameysharp/corrode.git
git clone https://github.com/ghc/ghc.git
git clone https://github.com/jgm/gitit.git
git clone https://github.com/lamdu/lamdu.git
git clone https://github.com/mikeizbicki/HLearn.git
git clone https://github.com/valderman/haste-compiler.git
git clone https://github.com/typelead/eta.git
git clone https://github.com/faylang/fay.git
git clone https://github.com/unisonweb/unison.git
git clone https://github.com/yi-editor/yi.git
git clone https://github.com/scotty-web/scotty.git
git clone https://github.com/ekmett/lens.git
git clone https://github.com/sdiehl/wiwinwlh.git
git clone https://github.com/olivierverdier/zsh-git-prompt.git
git clone https://github.com/GaloisInc/HaLVM.git
git clone https://github.com/jaspervdj/patat.git
git clone https://github.com/oden-lang/oden.git
git clone https://github.com/huangz1990/real-world-haskell-cn.git
git clone https://github.com/haskell-servant/servant.git
git clone https://github.com/haskell/cabal.git
git clone https://github.com/hzlmn/haskell-must-watch.git
git clone https://github.com/avh4/elm-format.git
git clone https://github.com/awgn/cgrep.git
git clone https://github.com/leksah/leksah.git
git clone https://github.com/tonymorris/course.git
git clone https://github.com/bos/stanford-cs240h.git
git clone https://github.com/bos/aeson.git
git clone https://github.com/GaloisInc/cryptol.git
git clone https://github.com/ajtulloch/dnngraph.git
git clone https://github.com/elm-lang/elm-platform.git
git clone https://github.com/xmonad/xmonad.git
git clone https://github.com/aurapm/aura.git
git clone https://github.com/lukasmartinelli/hadolint.git
git clone https://github.com/commercialhaskell/intero.git
git clone https://github.com/DanielG/ghc-mod.git
git clone https://github.com/colah/ImplicitCAD.git
git clone https://github.com/thoughtbot/carnival.git
git clone https://github.com/z0w0/helm.git
git clone https://github.com/BinRoot/Haskell-Data-Analysis-Cookbook.git
git clone https://github.com/quchen/articles.git
git clone https://github.com/sdiehl/kaleidoscope.git
git clone https://github.com/google/codeworld.git
git clone https://github.com/tensorflow/haskell.git
git clone https://github.com/mattgreen/hython.git
git clone https://github.com/ChrisPenner/rasa.git
git clone https://github.com/haskell-distributed/distributed-process.git
git clone https://github.com/chrisdone/hell.git
git clone https://github.com/AccelerateHS/accelerate.git
git clone https://github.com/tidalcycles/Tidal.git
git clone https://github.com/joshuaclayton/unused.git
git clone https://github.com/evincarofautumn/kitten.git
git clone https://github.com/Gabriel439/Haskell-Turtle-Library.git
git clone https://github.com/simonmichael/hledger.git
git clone https://github.com/yesodweb/wai.git
git clone https://github.com/haskell/haskell-ide-engine.git
git clone https://github.com/clash-lang/clash-compiler.git
git clone https://github.com/kirel/detexify-hs-backend.git
git clone https://github.com/fptudelft/FP101x-Content-2015.git
git clone https://github.com/rgleichman/glance.git
git clone https://github.com/ndmitchell/shake.git
git clone https://github.com/agrafix/Spock.git
git clone https://github.com/ndmitchell/hlint.git
git clone https://github.com/kadena-io/juno.git
git clone https://github.com/egison/egison.git
git clone https://github.com/reflex-frp/reflex.git
git clone https://github.com/snoyberg/conduit.git
git clone https://github.com/silkapp/rest.git
git clone https://github.com/snapframework/snap.git
git clone https://github.com/jaspervdj/stylish-haskell.git
git clone https://github.com/BurntSushi/erd.git
git clone https://github.com/hspec/hspec.git
git clone https://github.com/elm-lang/elm-reactor.git
git clone https://github.com/JakeWheat/intro_to_parsing.git
git clone https://github.com/jepst/CloudHaskell.git
git clone https://github.com/ananthakumaran/webify.git
git clone https://github.com/ucsd-progsys/liquidhaskell.git
git clone https://github.com/jbarrow/LambdaNet.git
git clone https://github.com/transient-haskell/transient.git
git clone https://github.com/davidbrewer/xmonad-ubuntu-conf.git
git clone https://github.com/HeinrichApfelmus/reactive-banana.git
git clone https://github.com/vicfryzel/xmonad-config.git
git clone https://github.com/pcapriotti/optparse-applicative.git
git clone https://github.com/Gabriel439/Haskell-Pipes-Library.git
git clone https://github.com/haskoin/haskoin.git
git clone https://github.com/mikeizbicki/subhask.git
git clone https://github.com/mbrubeck/compleat.git
git clone https://github.com/vincenthz/hs-tls.git
