mkdir -p JavaScript
cd JavaScript
git clone https://github.com/freeCodeCamp/freeCodeCamp.git
git clone https://github.com/twbs/bootstrap.git
git clone https://github.com/facebook/react.git
git clone https://github.com/d3/d3.git
git clone https://github.com/angular/angular.js.git
git clone https://github.com/getify/You-Dont-Know-JS.git
git clone https://github.com/airbnb/javascript.git
git clone https://github.com/vuejs/vue.git
git clone https://github.com/facebook/react-native.git
git clone https://github.com/jquery/jquery.git
git clone https://github.com/meteor/meteor.git
git clone https://github.com/h5bp/html5-boilerplate.git
git clone https://github.com/hakimel/reveal.js.git
git clone https://github.com/nodejs/node.git
git clone https://github.com/Semantic-Org/Semantic-UI.git
git clone https://github.com/mrdoob/three.js.git
git clone https://github.com/socketio/socket.io.git
git clone https://github.com/impress/impress.js.git
git clone https://github.com/expressjs/express.git
git clone https://github.com/moment/moment.git
git clone https://github.com/reactjs/redux.git
git clone https://github.com/chartjs/Chart.js.git
git clone https://github.com/adobe/brackets.git
git clone https://github.com/resume/resume.github.com.git
git clone https://github.com/NARKOZ/hacker-scripts.git
git clone https://github.com/blueimp/jQuery-File-Upload.git
git clone https://github.com/jashkenas/backbone.git
git clone https://github.com/gulpjs/gulp.git
git clone https://github.com/webpack/webpack.git
git clone https://github.com/Dogfalo/materialize.git
git clone https://github.com/zurb/foundation-sites.git
git clone https://github.com/callemall/material-ui.git
git clone https://github.com/yarnpkg/yarn.git
git clone https://github.com/facebookincubator/create-react-app.git
git clone https://github.com/TryGhost/Ghost.git
git clone https://github.com/lodash/lodash.git
git clone https://github.com/nylas/nylas-mail.git
git clone https://github.com/caolan/async.git
git clone https://github.com/ReactTraining/react-router.git
git clone https://github.com/tastejs/todomvc.git
git clone https://github.com/jashkenas/underscore.git
git clone https://github.com/babel/babel.git
git clone https://github.com/Modernizr/Modernizr.git
git clone https://github.com/typicode/json-server.git
git clone https://github.com/select2/select2.git
git clone https://github.com/adam-p/markdown-here.git
git clone https://github.com/alvarotrigo/fullPage.js.git
git clone https://github.com/Leaflet/Leaflet.git
git clone https://github.com/Unitech/pm2.git
git clone https://github.com/facebook/immutable-js.git
git clone https://github.com/emberjs/ember.js.git
git clone https://github.com/kenwheeler/slick.git
git clone https://github.com/mozilla/pdf.js.git
git clone https://github.com/justjavac/free-programming-books-zh_CN.git
git clone https://github.com/balderdashy/sails.git
git clone https://github.com/ecomfe/echarts.git
git clone https://github.com/zenorocha/clipboard.js.git
git clone https://github.com/hammerjs/hammer.js.git
git clone https://github.com/zeit/hyper.git
git clone https://github.com/videojs/video.js.git
git clone https://github.com/bevacqua/dragula.git
git clone https://github.com/t4t5/sweetalert.git
git clone https://github.com/angular/material.git
git clone https://github.com/mzabriskie/axios.git
git clone https://github.com/hexojs/hexo.git
git clone https://github.com/serverless/serverless.git
git clone https://github.com/bower/bower.git
git clone https://github.com/Reactive-Extensions/RxJS.git
git clone https://github.com/defunkt/jquery-pjax.git
git clone https://github.com/request/request.git
git clone https://github.com/GitbookIO/gitbook.git
git clone https://github.com/Kickball/awesome-selfhosted.git
git clone https://github.com/less/less.js.git
git clone https://github.com/ajaxorg/ace.git
git clone https://github.com/koajs/koa.git
git clone https://github.com/petkaantonov/bluebird.git
git clone https://github.com/aosabook/500lines.git
git clone https://github.com/postcss/postcss.git
git clone https://github.com/twitter/typeahead.js.git
git clone https://github.com/angular-ui/bootstrap.git
git clone https://github.com/pugjs/pug.git
git clone https://github.com/pixijs/pixi.js.git
git clone https://github.com/facebook/flux.git
git clone https://github.com/dimsemenov/PhotoSwipe.git
git clone https://github.com/lord/slate.git
git clone https://github.com/github/fetch.git
git clone https://github.com/kriasoft/react-starter-kit.git
git clone https://github.com/ParsePlatform/parse-server.git
git clone https://github.com/kriskowal/q.git
git clone https://github.com/rstacruz/nprogress.git
git clone https://github.com/feross/webtorrent.git
git clone https://github.com/react-boilerplate/react-boilerplate.git
git clone https://github.com/angular/angular-seed.git
git clone https://github.com/quilljs/quill.git
git clone https://github.com/ryanmcdermott/clean-code-javascript.git
git clone https://github.com/julianshapiro/velocity.git
git clone https://github.com/knsv/mermaid.git
git clone https://github.com/jasmine/jasmine.git
git clone https://github.com/verekia/js-stack-from-scratch.git
git clone https://github.com/npm/npm.git
