mkdir -p Java
cd Java
git clone https://github.com/ReactiveX/RxJava.git
git clone https://github.com/elastic/elasticsearch.git
git clone https://github.com/square/retrofit.git
git clone https://github.com/square/okhttp.git
git clone https://github.com/iluwatar/java-design-patterns.git
git clone https://github.com/google/guava.git
git clone https://github.com/JakeWharton/butterknife.git
git clone https://github.com/nostra13/Android-Universal-Image-Loader.git
git clone https://github.com/PhilJay/MPAndroidChart.git
git clone https://github.com/square/leakcanary.git
git clone https://github.com/bumptech/glide.git
git clone https://github.com/greenrobot/EventBus.git
git clone https://github.com/google/iosched.git
git clone https://github.com/square/picasso.git
git clone https://github.com/spring-projects/spring-framework.git
git clone https://github.com/zxing/zxing.git
git clone https://github.com/facebook/fresco.git
git clone https://github.com/ReactiveX/RxAndroid.git
git clone https://github.com/libgdx/libgdx.git
git clone https://github.com/spring-projects/spring-boot.git
git clone https://github.com/airbnb/lottie-android.git
git clone https://github.com/jfeinstein10/SlidingMenu.git
git clone https://github.com/loopj/android-async-http.git
git clone https://github.com/netty/netty.git
git clone https://github.com/chrisbanes/PhotoView.git
git clone https://github.com/androidannotations/androidannotations.git
git clone https://github.com/afollestad/material-dialogs.git
git clone https://github.com/nathanmarz/storm.git
git clone https://github.com/Netflix/Hystrix.git
git clone https://github.com/JakeWharton/ViewPagerIndicator.git
git clone https://github.com/lgvalle/Material-Animations.git
git clone https://github.com/pockethub/PocketHub.git
git clone https://github.com/Blankj/AndroidUtilCode.git
git clone https://github.com/nickbutcher/plaid.git
git clone https://github.com/alibaba/fastjson.git
git clone https://github.com/Tencent/tinker.git
git clone https://github.com/chrisbanes/Android-PullToRefresh.git
git clone https://github.com/android10/Android-CleanArchitecture.git
git clone https://github.com/navasmdc/MaterialDesignLibrary.git
git clone https://github.com/alibaba/dubbo.git
git clone https://github.com/HannahMitt/HomeMirror.git
git clone https://github.com/daimajia/AndroidSwipeLayout.git
git clone https://github.com/liaohuqiu/android-Ultra-Pull-To-Refresh.git
git clone https://github.com/JakeWharton/ActionBarSherlock.git
git clone https://github.com/JetBrains/kotlin.git
git clone https://github.com/realm/realm-java.git
git clone https://github.com/googlesamples/android-UniversalMusicPlayer.git
git clone https://github.com/ksoichiro/Android-ObservableScrollView.git
git clone https://github.com/mikepenz/MaterialDrawer.git
git clone https://github.com/facebook/stetho.git
git clone https://github.com/greenrobot/greenDAO.git
git clone https://github.com/daimajia/AndroidViewAnimations.git
git clone https://github.com/EnterpriseQualityCoding/FizzBuzzEnterpriseEdition.git
git clone https://github.com/google/flexbox-layout.git
git clone https://github.com/winterbe/java8-tutorial.git
git clone https://github.com/chrisbanes/cheesesquare.git
git clone https://github.com/hdodenhof/CircleImageView.git
git clone https://github.com/google/agera.git
git clone https://github.com/clojure/clojure.git
git clone https://github.com/square/dagger.git
git clone https://github.com/google/ExoPlayer.git
git clone https://github.com/CymChad/BaseRecyclerViewAdapterHelper.git
git clone https://github.com/umano/AndroidSlidingUpPanel.git
git clone https://github.com/bazelbuild/bazel.git
git clone https://github.com/orhanobut/logger.git
git clone https://github.com/astuetz/PagerSlidingTabStrip.git
git clone https://github.com/chrisjenx/Calligraphy.git
git clone https://github.com/android/platform_frameworks_base.git
git clone https://github.com/apl-devs/AppIntro.git
git clone https://github.com/google/physical-web.git
git clone https://github.com/Bearded-Hen/Android-Bootstrap.git
git clone https://github.com/perwendel/spark.git
git clone https://github.com/eclipse/vert.x.git
git clone https://github.com/roughike/BottomBar.git
git clone https://github.com/junit-team/junit4.git
git clone https://github.com/florent37/MaterialViewPager.git
git clone https://github.com/deeplearning4j/deeplearning4j.git
git clone https://github.com/prestodb/presto.git
git clone https://github.com/alibaba/druid.git
git clone https://github.com/wasabeef/recyclerview-animators.git
git clone https://github.com/LMAX-Exchange/disruptor.git
git clone https://github.com/Freelander/Android_Data.git
git clone https://github.com/nhaarman/ListViewAnimations.git
git clone https://github.com/dropwizard/dropwizard.git
git clone https://github.com/openzipkin/zipkin.git
git clone https://github.com/Netflix/SimianArmy.git
git clone https://github.com/koush/ion.git
git clone https://github.com/cymcsg/UltimateRecyclerView.git
git clone https://github.com/JakeWharton/RxBinding.git
git clone https://github.com/wyouflf/xUtils.git
git clone https://github.com/JackyAndroid/AndroidInterview-Q-A.git
git clone https://github.com/Bilibili/DanmakuFlameMaster.git
git clone https://github.com/hongyangAndroid/okhttputils.git
git clone https://github.com/kaushikgopal/RxJava-Android-Samples.git
git clone https://github.com/xetorthio/jedis.git
git clone https://github.com/apache/kafka.git
git clone https://github.com/google/guice.git
git clone https://github.com/dropwizard/metrics.git
git clone https://github.com/square/otto.git
git clone https://github.com/geeeeeeeeek/WeChatLuckyMoney.git
