sh C.sh &
sh Cpp.sh &
sh CSharp.sh &
sh Objective-C.sh &
sh Go.sh &
sh Java.sh &
sh CoffeeScript.sh &
sh JavaScript.sh &
sh TypeScript.sh &
sh Ruby.sh &
sh PHP.sh &
sh Python.sh &
sh Perl.sh &
sh Clojure.sh &
sh Erlang.sh &
sh Haskell.sh &
sh Scala.sh &
sh Swift.sh &
