mkdir -p Objective-C
cd Objective-C
git clone https://github.com/AFNetworking/AFNetworking.git
git clone https://github.com/rs/SDWebImage.git
git clone https://github.com/BradLarson/GPUImage.git
git clone https://github.com/SnapKit/Masonry.git
git clone https://github.com/jdg/MBProgressHUD.git
git clone https://github.com/ccgus/fmdb.git
git clone https://github.com/Mantle/Mantle.git
git clone https://github.com/realm/realm-cocoa.git
git clone https://github.com/magicalpanda/MagicalRecord.git
git clone https://github.com/CoderMJLee/MJRefresh.git
git clone https://github.com/jessesquires/JSQMessagesViewController.git
git clone https://github.com/RestKit/RestKit.git
git clone https://github.com/alcatraz/Alcatraz.git
git clone https://github.com/bang590/JSPatch.git
git clone https://github.com/ibireme/YYKit.git
git clone https://github.com/SVProgressHUD/SVProgressHUD.git
git clone https://github.com/nicklockwood/iCarousel.git
git clone https://github.com/CocoaLumberjack/CocoaLumberjack.git
git clone https://github.com/ViccAlexander/Chameleon.git
git clone https://github.com/hackiftekhar/IQKeyboardManager.git
git clone https://github.com/robbiehanson/CocoaAsyncSocket.git
git clone https://github.com/onevcat/VVDocumenter-Xcode.git
git clone https://github.com/marcuswestin/WebViewJavascriptBridge.git
git clone https://github.com/kevinzhow/PNChart.git
git clone https://github.com/dzenbot/DZNEmptyDataSet.git
git clone https://github.com/facebook/Shimmer.git
git clone https://github.com/facebookarchive/three20.git
git clone https://github.com/matryer/bitbar.git
git clone https://github.com/Flipboard/FLEX.git
git clone https://github.com/slackhq/SlackTextViewController.git
git clone https://github.com/Grouper/FlatUIKit.git
git clone https://github.com/OpenEmu/OpenEmu.git
git clone https://github.com/path/FastImageCache.git
git clone https://github.com/TTTAttributedLabel/TTTAttributedLabel.git
git clone https://github.com/eczarny/spectacle.git
git clone https://github.com/forkingdog/UITableView-FDTemplateLayoutCell.git
git clone https://github.com/mwaterfall/MWPhotoBrowser.git
git clone https://github.com/airbnb/lottie-ios.git
git clone https://github.com/Aufree/trip-to-iOS.git
git clone https://github.com/romaonthego/RESideMenu.git
git clone https://github.com/CoderMJLee/MJExtension.git
git clone https://github.com/CEWendel/SWTableViewCell.git
git clone https://github.com/facebook/SocketRocket.git
git clone https://github.com/jigish/slate.git
git clone https://github.com/git-up/GitUp.git
git clone https://github.com/facebook/xctool.git
git clone https://github.com/jverkoey/nimbus.git
git clone https://github.com/PureLayout/PureLayout.git
git clone https://github.com/tonymillion/Reachability.git
git clone https://github.com/jverdi/JVFloatLabeledTextField.git
git clone https://github.com/IFTTT/JazzHands.git
git clone https://github.com/johnezang/JSONKit.git
git clone https://github.com/ibireme/YYText.git
git clone https://github.com/mutualmobile/MMDrawerController.git
git clone https://github.com/zwaldowski/BlocksKit.git
git clone https://github.com/jsonmodel/jsonmodel.git
git clone https://github.com/pokeb/asi-http-request.git
git clone https://github.com/facebook/facebook-ios-sdk.git
git clone https://github.com/Kapeli/Dash-iOS.git
git clone https://github.com/MacDownApp/macdown.git
git clone https://github.com/gnachman/iTerm2.git
git clone https://github.com/Flipboard/FLAnimatedImage.git
git clone https://github.com/facebook/KVOController.git
git clone https://github.com/square/PonyDebugger.git
git clone https://github.com/nst/iOS-Runtime-Headers.git
git clone https://github.com/MatthewYork/DateTools.git
git clone https://github.com/schneiderandre/popping.git
git clone https://github.com/CanvasPod/Canvas.git
git clone https://github.com/michaeltyson/TPKeyboardAvoiding.git
git clone https://github.com/ViewDeck/ViewDeck.git
git clone https://github.com/levey/AwesomeMenu.git
git clone https://github.com/mamaral/Onboard.git
git clone https://github.com/MortimerGoro/MGSwipeTableCell.git
git clone https://github.com/BoltsFramework/Bolts-ObjC.git
git clone https://github.com/robbiehanson/XMPPFramework.git
git clone https://github.com/ChenYilong/iOSInterviewQuestions.git
git clone https://github.com/Instagram/IGListKit.git
git clone https://github.com/XVimProject/XVim.git
git clone https://github.com/nicklockwood/FXBlurView.git
git clone https://github.com/steipete/Aspects.git
git clone https://github.com/Cocoanetics/DTCoreText.git
git clone https://github.com/ResearchKit/ResearchKit.git
git clone https://github.com/KrauseFx/TSMessages.git
git clone https://github.com/kif-framework/KIF.git
git clone https://github.com/samvermette/SVPullToRefresh.git
git clone https://github.com/samuelclay/NewsBlur.git
git clone https://github.com/shadowsocks/shadowsocks-iOS.git
git clone https://github.com/facebook/Tweaks.git
git clone https://github.com/CSStickyHeaderFlowLayout/CSStickyHeaderFlowLayout.git
git clone https://github.com/johnno1962/injectionforxcode.git
git clone https://github.com/ChenYilong/iOS9AdaptationTips.git
git clone https://github.com/ECSlidingViewController/ECSlidingViewController.git
git clone https://github.com/arashpayan/appirater.git
git clone https://github.com/meili/TeamTalk.git
git clone https://github.com/Jasonette/JASONETTE-iOS.git
git clone https://github.com/xmartlabs/XLForm.git
git clone https://github.com/ksuther/KSImageNamed-Xcode.git
git clone https://github.com/soffes/SAMKeychain.git
git clone https://github.com/gsdios/SDAutoLayout.git
git clone https://github.com/tonsky/AnyBar.git
