mkdir -p Perl
cd Perl
git clone https://github.com/so-fancy/diff-so-fancy.git
git clone https://github.com/sitaramc/gitolite.git
git clone https://github.com/Jack000/Expose.git
git clone https://github.com/major/MySQLTuner-perl.git
git clone https://github.com/AlDanial/cloc.git
git clone https://github.com/sarabander/sicp-pdf.git
git clone https://github.com/tobie/ua-parser.git
git clone https://github.com/kraih/mojo.git
git clone https://github.com/openresty/nginx-tutorials.git
git clone https://github.com/thoughtbot/rcm.git
git clone https://github.com/sullo/nikto.git
git clone https://github.com/petdance/ack2.git
git clone https://github.com/duckduckgo/duckduckgo.git
git clone https://github.com/theory/sqitch.git
git clone https://github.com/jlord/git-it-electron.git
git clone https://github.com/dalibo/pgbadger.git
git clone https://github.com/CNSRE/ABTestingGateway.git
git clone https://github.com/k4rthik/git-cal.git
git clone https://github.com/munin-monitoring/munin.git
git clone https://github.com/munin-monitoring/contrib.git
git clone https://github.com/creaktive/rainbarf.git
git clone https://github.com/lulzlabs/AirChat.git
git clone https://github.com/fletcher/MultiMarkdown.git
git clone https://github.com/prey/prey-bash-client.git
git clone https://github.com/jessfraz/dotfiles.git
git clone https://github.com/SpiderLabs/owasp-modsecurity-crs.git
git clone https://github.com/GUI/lua-resty-auto-ssl.git
git clone https://github.com/petdance/ack.git
git clone https://github.com/rsnapshot/rsnapshot.git
git clone https://github.com/PenturaLabs/Linux_Exploit_Suggester.git
git clone https://github.com/webfrogs/xcode_shell.git
git clone https://github.com/git-deploy/git-deploy.git
git clone https://github.com/PerlDancer/Dancer.git
git clone https://github.com/imapsync/imapsync.git
git clone https://github.com/openresty/openresty-systemtap-toolkit.git
git clone https://github.com/yuki-kimoto/gitprep.git
git clone https://github.com/get-iplayer/get_iplayer.git
git clone https://github.com/jonreid/XcodeCoverage.git
git clone https://github.com/hokaccha/nodebrew.git
git clone https://github.com/agentzh/code2ebook.git
git clone https://github.com/duckduckgo/zeroclickinfo-goodies.git
git clone https://github.com/nferraz/st.git
git clone https://github.com/chromatic/modern_perl_book.git
git clone https://github.com/StefanSchroeder/Golang-Regex-Tutorial.git
git clone https://github.com/miyagawa/cpanminus.git
git clone https://github.com/gugod/App-perlbrew.git
git clone https://github.com/pasky/speedread.git
git clone https://github.com/RexOps/Rex.git
git clone https://github.com/muennich/urxvt-perls.git
git clone https://github.com/webmin/webmin.git
git clone https://github.com/infobyte/evilgrade.git
git clone https://github.com/sjdy521/Mojo-Webqq.git
git clone https://github.com/HariSekhon/nagios-plugins.git
git clone https://github.com/Nordaaker/convos.git
git clone https://github.com/huichen/mlf.git
git clone https://github.com/linode/cli.git
git clone https://github.com/plack/Plack.git
git clone https://github.com/vsespb/mt-aws-glacier.git
git clone https://github.com/kost/dvcs-ripper.git
git clone https://github.com/jimsalterjrs/sanoid.git
git clone https://github.com/jfhovinne/jFeed.git
git clone https://github.com/mikaku/Monitorix.git
git clone https://github.com/mattiasgeniar/varnish-4.0-configuration-templates.git
git clone https://github.com/weijianwen/SJTUThesis.git
git clone https://github.com/skx/sysadmin-util.git
git clone https://github.com/perl-carton/carton.git
git clone https://github.com/dotphiles/dotphiles.git
git clone https://github.com/ljunkie/plexWatch.git
git clone https://github.com/alestic/ec2-consistent-snapshot.git
git clone https://github.com/p0pr0ck5/lua-resty-waf.git
git clone https://github.com/philovivero/distribution.git
git clone https://github.com/mrnugget/opencv-haar-classifier-training.git
git clone https://github.com/PerlDancer/Dancer2.git
git clone https://github.com/duncs/clusterssh.git
git clone https://github.com/bestpractical/rt.git
git clone https://github.com/iberianpig/xSwipe.git
git clone https://github.com/timkay/aws.git
git clone https://github.com/freebsdgirl/ggautoblocker.git
git clone https://github.com/sjdy521/Mojo-Weixin.git
git clone https://github.com/jbittel/httpry.git
git clone https://github.com/trapd00r/ls--.git
git clone https://github.com/mattiasgeniar/varnish-3.0-configuration-templates.git
git clone https://github.com/andrewning/sortphotos.git
git clone https://github.com/hachiojipm/awesome-perl.git
git clone https://github.com/OpenKore/openkore.git
git clone https://github.com/irssi/scripts.irssi.org.git
git clone https://github.com/metabrainz/musicbrainz-server.git
git clone https://github.com/Logitech/slimserver.git
git clone https://github.com/mysociety/fixmystreet.git
git clone https://github.com/yoshinorim/mha4mysql-manager.git
git clone https://github.com/movabletype/movabletype.git
git clone https://github.com/swcarpentry/DEPRECATED-bc.git
git clone https://github.com/linode/longview.git
git clone https://github.com/OTRS/otrs.git
git clone https://github.com/electro7/dotfiles.git
git clone https://github.com/lamw/vghetto-scripts.git
git clone https://github.com/leedo/noembed.git
git clone https://github.com/yaoweibin/ngx_http_substitutions_filter_module.git
git clone https://github.com/Perl/perl5.git
git clone https://github.com/xypiie/spread0r.git
