mkdir -p PHP
cd PHP
git clone https://github.com/laravel/laravel.git
git clone https://github.com/symfony/symfony.git
git clone https://github.com/bcit-ci/CodeIgniter.git
git clone https://github.com/domnikl/DesignPatternsPHP.git
git clone https://github.com/fzaninotto/Faker.git
git clone https://github.com/yiisoft/yii2.git
git clone https://github.com/composer/composer.git
git clone https://github.com/WordPress/WordPress.git
git clone https://github.com/guzzle/guzzle.git
git clone https://github.com/PHPMailer/PHPMailer.git
git clone https://github.com/roots/sage.git
git clone https://github.com/phacility/phabricator.git
git clone https://github.com/PHPOffice/PHPExcel.git
git clone https://github.com/slimphp/Slim.git
git clone https://github.com/phalcon/cphalcon.git
git clone https://github.com/phanan/koel.git
git clone https://github.com/piwik/piwik.git
git clone https://github.com/cakephp/cakephp.git
git clone https://github.com/laravel/framework.git
git clone https://github.com/serbanghita/Mobile-Detect.git
git clone https://github.com/getgrav/grav.git
git clone https://github.com/CachetHQ/Cachet.git
git clone https://github.com/sebastianbergmann/phpunit.git
git clone https://github.com/Seldaek/monolog.git
git clone https://github.com/twostairs/paperwork.git
git clone https://github.com/octobercms/october.git
git clone https://github.com/dingo/api.git
git clone https://github.com/briannesbitt/Carbon.git
git clone https://github.com/danielmiessler/SecLists.git
git clone https://github.com/owncloud/core.git
git clone https://github.com/FriendsOfPHP/Goutte.git
git clone https://github.com/reactphp/react.git
git clone https://github.com/Intervention/image.git
git clone https://github.com/yiisoft/yii.git
git clone https://github.com/barryvdh/laravel-debugbar.git
git clone https://github.com/laravel/lumen.git
git clone https://github.com/justinwalsh/daux.io.git
git clone https://github.com/barryvdh/laravel-ide-helper.git
git clone https://github.com/Zizaco/entrust.git
git clone https://github.com/google/google-api-php-client.git
git clone https://github.com/FriendsOfPHP/PHP-CS-Fixer.git
git clone https://github.com/DevinVinson/WordPress-Plugin-Boilerplate.git
git clone https://github.com/magento/magento2.git
git clone https://github.com/overtrue/wechat.git
git clone https://github.com/erusev/parsedown.git
git clone https://github.com/pagekit/pagekit.git
git clone https://github.com/walkor/Workerman.git
git clone https://github.com/filp/whoops.git
git clone https://github.com/WP-API/WP-API.git
git clone https://github.com/humhub/humhub.git
git clone https://github.com/Respect/Validation.git
git clone https://github.com/isohuntto/openbay.git
git clone https://github.com/Varying-Vagrant-Vagrants/VVV.git
git clone https://github.com/deployphp/deployer.git
git clone https://github.com/twigphp/Twig.git
git clone https://github.com/silexphp/Silex.git
git clone https://github.com/doctrine/doctrine2.git
git clone https://github.com/facebookarchive/facebook-php-sdk.git
git clone https://github.com/dompdf/dompdf.git
git clone https://github.com/kriswallsmith/assetic.git
git clone https://github.com/ThinkUpLLC/ThinkUp.git
git clone https://github.com/ratchetphp/Ratchet.git
git clone https://github.com/nemoTyrant/manong.git
git clone https://github.com/electerious/Lychee.git
git clone https://github.com/tymondesigns/jwt-auth.git
git clone https://github.com/abraham/twitteroauth.git
git clone https://github.com/roots/bedrock.git
git clone https://github.com/nrk/predis.git
git clone https://github.com/dodgepudding/wechat-php-sdk.git
git clone https://github.com/vlucas/phpdotenv.git
git clone https://github.com/squizlabs/PHP_CodeSniffer.git
git clone https://github.com/thephpleague/flysystem.git
git clone https://github.com/opencart/opencart.git
git clone https://github.com/woocommerce/woocommerce.git
git clone https://github.com/wp-cli/wp-cli.git
git clone https://github.com/bolt/bolt.git
git clone https://github.com/timber/timber.git
git clone https://github.com/pattern-lab/patternlab-php.git
git clone https://github.com/JeffreyWay/Laravel-4-Generators.git
git clone https://github.com/Maatwebsite/Laravel-Excel.git
git clone https://github.com/mgp25/Chat-API.git
git clone https://github.com/avalanche123/Imagine.git
git clone https://github.com/mledoze/countries.git
git clone https://github.com/geocoder-php/Geocoder.git
git clone https://github.com/YOURLS/YOURLS.git
git clone https://github.com/typecho/typecho.git
git clone https://github.com/anchorcms/anchor-cms.git
git clone https://github.com/flarum/core.git
git clone https://github.com/Sylius/Sylius.git
git clone https://github.com/php-pm/php-pm.git
git clone https://github.com/robmorgan/phinx.git
git clone https://github.com/fex-team/fis.git
git clone https://github.com/nikic/PHP-Parser.git
git clone https://github.com/thephpleague/oauth2-server.git
git clone https://github.com/Codeception/Codeception.git
git clone https://github.com/the-control-group/voyager.git
git clone https://github.com/top-think/think.git
git clone https://github.com/chrisboulton/php-resque.git
git clone https://github.com/wallabag/wallabag.git
git clone https://github.com/TechEmpower/FrameworkBenchmarks.git
