mkdir -p Python
cd Python
git clone https://github.com/vinta/awesome-python.git
git clone https://github.com/jakubroztocil/httpie.git
git clone https://github.com/pallets/flask.git
git clone https://github.com/nvbn/thefuck.git
git clone https://github.com/rg3/youtube-dl.git
git clone https://github.com/django/django.git
git clone https://github.com/kennethreitz/requests.git
git clone https://github.com/ansible/ansible.git
git clone https://github.com/josephmisiti/awesome-machine-learning.git
git clone https://github.com/minimaxir/big-list-of-naughty-strings.git
git clone https://github.com/scrapy/scrapy.git
git clone https://github.com/certbot/certbot.git
git clone https://github.com/scikit-learn/scikit-learn.git
git clone https://github.com/shadowsocks/shadowsocks.git
git clone https://github.com/Valloric/YouCompleteMe.git
git clone https://github.com/isocpp/CppCoreGuidelines.git
git clone https://github.com/tornadoweb/tornado.git
git clone https://github.com/fchollet/keras.git
git clone https://github.com/XX-net/XX-Net.git
git clone https://github.com/reddit/reddit.git
git clone https://github.com/airbnb/superset.git
git clone https://github.com/tensorflow/models.git
git clone https://github.com/getsentry/sentry.git
git clone https://github.com/ipython/ipython.git
git clone https://github.com/soimort/you-get.git
git clone https://github.com/faif/python-patterns.git
git clone https://github.com/drduh/macOS-Security-and-Privacy-Guide.git
git clone https://github.com/adobe-fonts/source-code-pro.git
git clone https://github.com/songrotek/Deep-Learning-Papers-Reading-Roadmap.git
git clone https://github.com/docker/compose.git
git clone https://github.com/chrissimpkins/Hack.git
git clone https://github.com/pandas-dev/pandas.git
git clone https://github.com/equinusocio/material-theme.git
git clone https://github.com/dmlc/mxnet.git
git clone https://github.com/binux/pyspider.git
git clone https://github.com/donnemartin/system-design-primer.git
git clone https://github.com/fabric/fabric.git
git clone https://github.com/sqlmapproject/sqlmap.git
git clone https://github.com/Rochester-NRT/RocAlphaGo.git
git clone https://github.com/apenwarr/sshuttle.git
git clone https://github.com/fxsjy/jieba.git
git clone https://github.com/alexjc/neural-doodle.git
git clone https://github.com/tomchristie/django-rest-framework.git
git clone https://github.com/saltstack/salt.git
git clone https://github.com/donnemartin/data-science-ipython-notebooks.git
git clone https://github.com/mitmproxy/mitmproxy.git
git clone https://github.com/powerline/powerline.git
git clone https://github.com/nicolargo/glances.git
git clone https://github.com/mailpile/Mailpile.git
git clone https://github.com/python/cpython.git
git clone https://github.com/getpelican/pelican.git
git clone https://github.com/cmusatyalab/openface.git
git clone https://github.com/spotify/luigi.git
git clone https://github.com/celery/celery.git
git clone https://github.com/HelloZeroNet/ZeroNet.git
git clone https://github.com/alexjc/neural-enhance.git
git clone https://github.com/odoo/odoo.git
git clone https://github.com/getredash/redash.git
git clone https://github.com/home-assistant/home-assistant.git
git clone https://github.com/p-e-w/maybe.git
git clone https://github.com/mail-in-a-box/mailinabox.git
git clone https://github.com/sovereign/sovereign.git
git clone https://github.com/eliangcs/http-prompt.git
git clone https://github.com/deis/deis.git
git clone https://github.com/lra/mackup.git
git clone https://github.com/Theano/Theano.git
git clone https://github.com/boto/boto.git
git clone https://github.com/facebook/chisel.git
git clone https://github.com/beetbox/beets.git
git clone https://github.com/rushter/MLAlgorithms.git
git clone https://github.com/kivy/kivy.git
git clone https://github.com/StevenBlack/hosts.git
git clone https://github.com/bokeh/bokeh.git
git clone https://github.com/samshadwell/TrumpScript.git
git clone https://github.com/eriklindernoren/ML-From-Scratch.git
git clone https://github.com/dbcli/pgcli.git
git clone https://github.com/clips/pattern.git
git clone https://github.com/phusion/baseimage-docker.git
git clone https://github.com/gleitz/howdoi.git
git clone https://github.com/wting/autojump.git
git clone https://github.com/openai/gym.git
git clone https://github.com/tflearn/tflearn.git
git clone https://github.com/nate-parrott/Flashlight.git
git clone https://github.com/channelcat/sanic.git
git clone https://github.com/docopt/docopt.git
git clone https://github.com/bup/bup.git
git clone https://github.com/matplotlib/matplotlib.git
git clone https://github.com/openai/universe.git
git clone https://github.com/scrapinghub/portia.git
git clone https://github.com/locustio/locust.git
git clone https://github.com/andymccurdy/redis-py.git
git clone https://github.com/chriskiehl/Gooey.git
git clone https://github.com/numenta/nupic.git
git clone https://github.com/USArmyResearchLab/Dshell.git
git clone https://github.com/jwilder/nginx-proxy.git
git clone https://github.com/wifiphisher/wifiphisher.git
git clone https://github.com/sivel/speedtest-cli.git
git clone https://github.com/divio/django-cms.git
git clone https://github.com/donnemartin/gitsome.git
git clone https://github.com/aws/aws-cli.git
