mkdir -p Ruby
cd Ruby
git clone https://github.com/rails/rails.git
git clone https://github.com/Homebrew/legacy-homebrew.git
git clone https://github.com/jekyll/jekyll.git
git clone https://github.com/discourse/discourse.git
git clone https://github.com/gitlabhq/gitlabhq.git
git clone https://github.com/bayandin/awesome-awesomeness.git
git clone https://github.com/plataformatec/devise.git
git clone https://github.com/cantino/huginn.git
git clone https://github.com/fastlane/fastlane.git
git clone https://github.com/mitchellh/vagrant.git
git clone https://github.com/Thibaut/devdocs.git
git clone https://github.com/twbs/bootstrap-sass.git
git clone https://github.com/ruby/ruby.git
git clone https://github.com/diaspora/diaspora.git
git clone https://github.com/kilimchoi/engineering-blogs.git
git clone https://github.com/jondot/awesome-react-native.git
git clone https://github.com/caskroom/homebrew-cask.git
git clone https://github.com/imathis/octopress.git
git clone https://github.com/sass/sass.git
git clone https://github.com/capistrano/capistrano.git
git clone https://github.com/CocoaPods/CocoaPods.git
git clone https://github.com/sinatra/sinatra.git
git clone https://github.com/thoughtbot/paperclip.git
git clone https://github.com/spree/spree.git
git clone https://github.com/thoughtbot/bourbon.git
git clone https://github.com/rapid7/metasploit-framework.git
git clone https://github.com/ruby-grape/grape.git
git clone https://github.com/resque/resque.git
git clone https://github.com/teamcapybara/capybara.git
git clone https://github.com/jordansissel/fpm.git
git clone https://github.com/bbatsov/rubocop.git
git clone https://github.com/carrierwaveuploader/carrierwave.git
git clone https://github.com/mperham/sidekiq.git
git clone https://github.com/activeadmin/activeadmin.git
git clone https://github.com/elastic/logstash.git
git clone https://github.com/javan/whenever.git
git clone https://github.com/Homebrew/brew.git
git clone https://github.com/plataformatec/simple_form.git
git clone https://github.com/sferik/rails_admin.git
git clone https://github.com/tmuxinator/tmuxinator.git
git clone https://github.com/kaminari/kaminari.git
git clone https://github.com/thoughtbot/guides.git
git clone https://github.com/omniauth/omniauth.git
git clone https://github.com/ryanb/cancan.git
git clone https://github.com/charliesome/better_errors.git
git clone https://github.com/mame/quine-relay.git
git clone https://github.com/Tim9Liu9/TimLiu-iOS.git
git clone https://github.com/middleman/middleman.git
git clone https://github.com/progit/progit.git
git clone https://github.com/Shopify/liquid.git
git clone https://github.com/guard/guard.git
git clone https://github.com/skwp/dotfiles.git
git clone https://github.com/thoughtbot/factory_girl.git
git clone https://github.com/venmo/synx.git
git clone https://github.com/rails-api/rails-api.git
git clone https://github.com/fluent/fluentd.git
git clone https://github.com/elabs/pundit.git
git clone https://github.com/mislav/will_paginate.git
git clone https://github.com/cucumber/cucumber-ruby.git
git clone https://github.com/stympy/faker.git
git clone https://github.com/justinfrench/formtastic.git
git clone https://github.com/chef/chef.git
git clone https://github.com/puma/puma.git
git clone https://github.com/square/maximum-awesome.git
git clone https://github.com/pry/pry.git
git clone https://github.com/flyerhzm/bullet.git
git clone https://github.com/github/linguist.git
git clone https://github.com/airblade/paper_trail.git
git clone https://github.com/norman/friendly_id.git
git clone https://github.com/alexreisner/geocoder.git
git clone https://github.com/puppetlabs/puppet.git
git clone https://github.com/evil-icons/evil-icons.git
git clone https://github.com/slim-template/slim.git
git clone https://github.com/ddollar/foreman.git
git clone https://github.com/nomad/shenzhen.git
git clone https://github.com/realm/jazzy.git
git clone https://github.com/rails-api/active_model_serializers.git
git clone https://github.com/sferik/t.git
git clone https://github.com/backup/backup.git
git clone https://github.com/presidentbeef/brakeman.git
git clone https://github.com/drapergem/draper.git
git clone https://github.com/jnunemaker/httparty.git
git clone https://github.com/github/scientist.git
git clone https://github.com/fog/fog.git
git clone https://github.com/mbleigh/acts-as-taggable-on.git
git clone https://github.com/binarylogic/authlogic.git
git clone https://github.com/kneath/kss.git
git clone https://github.com/BBC-News/wraith.git
git clone https://github.com/bkeepers/dotenv.git
git clone https://github.com/rest-client/rest-client.git
git clone https://github.com/sferik/twitter.git
git clone https://github.com/mroth/lolcommits.git
git clone https://github.com/sj26/mailcatcher.git
git clone https://github.com/bundler/bundler.git
git clone https://github.com/hanami/hanami.git
git clone https://github.com/github/markup.git
git clone https://github.com/erikhuda/thor.git
git clone https://github.com/errbit/errbit.git
git clone https://github.com/activemerchant/active_merchant.git
git clone https://github.com/pluginaweek/state_machine.git
