mkdir -p Scala
cd Scala
git clone https://github.com/apache/spark.git
git clone https://github.com/apache/incubator-predictionio.git
git clone https://github.com/playframework/playframework.git
git clone https://github.com/scala/scala.git
git clone https://github.com/shadowsocks/shadowsocks-android.git
git clone https://github.com/akka/akka.git
git clone https://github.com/gitbucket/gitbucket.git
git clone https://github.com/twitter/finagle.git
git clone https://github.com/lhartikk/ArnoldC.git
git clone https://github.com/mesos/chronos.git
git clone https://github.com/yahoo/kafka-manager.git
git clone https://github.com/twitter/snowflake.git
git clone https://github.com/snowplow/snowplow.git
git clone https://github.com/mesosphere/marathon.git
git clone https://github.com/twitter/flockdb.git
git clone https://github.com/scalaz/scalaz.git
git clone https://github.com/rtyley/bfg-repo-cleaner.git
git clone https://github.com/ornicar/lila.git
git clone https://github.com/sbt/sbt.git
git clone https://github.com/fpinscala/fpinscala.git
git clone https://github.com/gatling/gatling.git
git clone https://github.com/scala-js/scala-js.git
git clone https://github.com/twitter/diffy.git
git clone https://github.com/twitter-archive/kestrel.git
git clone https://github.com/twitter/scalding.git
git clone https://github.com/spray/spray.git
git clone https://github.com/scala-native/scala-native.git
git clone https://github.com/scalatra/scalatra.git
git clone https://github.com/twitter/gizzard.git
git clone https://github.com/pocorall/scaloid.git
git clone https://github.com/scalanlp/breeze.git
git clone https://github.com/milessabin/shapeless.git
git clone https://github.com/MojoJolo/textteaser.git
git clone https://github.com/twitter/summingbird.git
git clone https://github.com/twitter/util.git
git clone https://github.com/slick/slick.git
git clone https://github.com/laurilehmijoki/s3_website.git
git clone https://github.com/typelevel/cats.git
git clone https://github.com/linkerd/linkerd.git
git clone https://github.com/intel-analytics/BigDL.git
git clone https://github.com/twitter/finatra.git
git clone https://github.com/lampepfl/dotty.git
git clone https://github.com/spark-jobserver/spark-jobserver.git
git clone https://github.com/mesos/spark.git
git clone https://github.com/twitter/algebird.git
git clone https://github.com/GravityLabs/goose.git
git clone https://github.com/PkmX/lcamera.git
git clone https://github.com/Netflix/atlas.git
git clone https://github.com/twitter/iago.git
git clone https://github.com/lagom/lagom.git
git clone https://github.com/jaliss/securesocial.git
git clone https://github.com/openwhisk/openwhisk.git
git clone https://github.com/rickynils/scalacheck.git
git clone https://github.com/guardian/grid.git
git clone https://github.com/ensime/ensime-server.git
git clone https://github.com/lihaoyi/Ammonite.git
git clone https://github.com/datastax/spark-cassandra-connector.git
git clone https://github.com/non/spire.git
git clone https://github.com/mpeltonen/sbt-idea.git
git clone https://github.com/lift/framework.git
git clone https://github.com/foundweekends/giter8.git
git clone https://github.com/lw-lin/CoolplaySpark.git
git clone https://github.com/finagle/finch.git
git clone https://github.com/amplab/shark.git
git clone https://github.com/killrweather/killrweather.git
git clone https://github.com/mauricio/postgresql-async.git
git clone https://github.com/tumblr/colossus.git
git clone https://github.com/quantifind/KafkaOffsetMonitor.git
git clone https://github.com/yahoojapan/objc2swift.git
git clone https://github.com/ThoughtWorksInc/Binding.scala.git
git clone https://github.com/scala-exercises/scala-exercises.git
git clone https://github.com/twitter/cassovary.git
git clone https://github.com/json4s/json4s.git
git clone https://github.com/filodb/FiloDB.git
git clone https://github.com/getquill/quill.git
git clone https://github.com/sksamuel/elastic4s.git
git clone https://github.com/kamon-io/Kamon.git
git clone https://github.com/paypal/squbs.git
git clone https://github.com/scala/pickling.git
git clone https://github.com/lihaoyi/Metascala.git
git clone https://github.com/eligosource/eventsourced.git
git clone https://github.com/alexarchambault/coursier.git
git clone https://github.com/pathikrit/better-files.git
git clone https://github.com/sbt/sbt-native-packager.git
git clone https://github.com/circe/circe.git
git clone https://github.com/japgolly/scalajs-react.git
git clone https://github.com/vkostyukov/scalacaster.git
git clone https://github.com/twitter/ostrich.git
git clone https://github.com/tpolecat/doobie.git
git clone https://github.com/scala/async.git
git clone https://github.com/outworkers/phantom.git
git clone https://github.com/lihaoyi/scala.rx.git
git clone https://github.com/functional-streams-for-scala/fs2.git
git clone https://github.com/akka/reactive-kafka.git
git clone https://github.com/scalikejdbc/scalikejdbc.git
git clone https://github.com/julien-truffaut/Monocle.git
git clone https://github.com/sryza/spark-timeseries.git
git clone https://github.com/monix/monix.git
git clone https://github.com/jrudolph/sbt-dependency-graph.git
git clone https://github.com/databricks/spark-csv.git
