mkdir -p Swift
cd Swift
git clone https://github.com/Alamofire/Alamofire.git
git clone https://github.com/vsouza/awesome-ios.git
git clone https://github.com/ReactiveCocoa/ReactiveCocoa.git
git clone https://github.com/SwiftyJSON/SwiftyJSON.git
git clone https://github.com/danielgindi/Charts.git
git clone https://github.com/dkhamsing/open-source-ios-apps.git
git clone https://github.com/ipader/SwiftGuide.git
git clone https://github.com/raywenderlich/swift-algorithm-club.git
git clone https://github.com/matteocrippa/awesome-swift.git
git clone https://github.com/PerfectlySoft/Perfect.git
git clone https://github.com/MengTo/Spring.git
git clone https://github.com/SnapKit/SnapKit.git
git clone https://github.com/Carthage/Carthage.git
git clone https://github.com/vapor/vapor.git
git clone https://github.com/allenwong/30DaysofSwift.git
git clone https://github.com/ReactiveX/RxSwift.git
git clone https://github.com/fullstackio/FlappySwift.git
git clone https://github.com/JohnCoates/Aerial.git
git clone https://github.com/onevcat/Kingfisher.git
git clone https://github.com/lkzhao/Hero.git
git clone https://github.com/ochococo/Design-Patterns-In-Swift.git
git clone https://github.com/CosmicMind/Material.git
git clone https://github.com/mxcl/PromiseKit.git
git clone https://github.com/mozilla-mobile/firefox-ios.git
git clone https://github.com/Ramotion/animated-tab-bar.git
git clone https://github.com/realm/SwiftLint.git
git clone https://github.com/Quick/Quick.git
git clone https://github.com/IBAnimatable/IBAnimatable.git
git clone https://github.com/xmartlabs/Eureka.git
git clone https://github.com/IBM-Swift/Kitura.git
git clone https://github.com/lexrus/LTMorphingLabel.git
git clone https://github.com/apple/swift-package-manager.git
git clone https://github.com/CatchChat/Yep.git
git clone https://github.com/Moya/Moya.git
git clone https://github.com/Ramotion/folding-cell.git
git clone https://github.com/robb/Cartography.git
git clone https://github.com/Hearst-DD/ObjectMapper.git
git clone https://github.com/insidegui/WWDC.git
git clone https://github.com/lhc70000/iina.git
git clone https://github.com/ninjaprox/NVActivityIndicatorView.git
git clone https://github.com/andreamazz/AMScrollingNavbar.git
git clone https://github.com/mortenjust/androidtool-mac.git
git clone https://github.com/JakeLin/SwiftWeather.git
git clone https://github.com/collinhundley/Swift-AI.git
git clone https://github.com/kickstarter/ios-oss.git
git clone https://github.com/Haneke/HanekeSwift.git
git clone https://github.com/nickoneill/PermissionScope.git
git clone https://github.com/duemunk/Async.git
git clone https://github.com/storehouse/Advance.git
git clone https://github.com/stephencelis/SQLite.swift.git
git clone https://github.com/mamaral/Neon.git
git clone https://github.com/ianyh/Amethyst.git
git clone https://github.com/uacaps/PageMenu.git
git clone https://github.com/raulriera/TextFieldEffects.git
git clone https://github.com/xmartlabs/XLPagerTabStrip.git
git clone https://github.com/vikmeup/SCLAlertView-Swift.git
git clone https://github.com/philackm/Scrollable-GraphView.git
git clone https://github.com/shu223/iOS-9-Sampler.git
git clone https://github.com/ankurp/Dollar.git
git clone https://github.com/mattt/Surge.git
git clone https://github.com/ashleymills/Reachability.swift.git
git clone https://github.com/krzyzanowskim/CryptoSwift.git
git clone https://github.com/ReSwift/ReSwift.git
git clone https://github.com/SwiftGen/SwiftGen.git
git clone https://github.com/mac-cain13/R.swift.git
git clone https://github.com/PostgresApp/PostgresApp.git
git clone https://github.com/kanaka/mal.git
git clone https://github.com/Ramotion/expanding-collection.git
git clone https://github.com/pNre/ExSwift.git
git clone https://github.com/SwiftCarlos/Swift.git
git clone https://github.com/mortenjust/cleartext-mac.git
git clone https://github.com/SwifterSwift/SwifterSwift.git
git clone https://github.com/lexrus/VPNOn.git
git clone https://github.com/thoughtbot/Argo.git
git clone https://github.com/ReactiveKit/Bond.git
git clone https://github.com/BradLarson/GPUImage2.git
git clone https://github.com/Yalantis/Koloda.git
git clone https://github.com/mas-cli/mas.git
git clone https://github.com/shu223/iOS-10-Sampler.git
git clone https://github.com/typelift/Swiftz.git
git clone https://github.com/yoavlt/LiquidFloatingActionButton.git
git clone https://github.com/Yalantis/StarWars.iOS.git
git clone https://github.com/malcommac/SwiftDate.git
git clone https://github.com/kishikawakatsumi/KeychainAccess.git
git clone https://github.com/okmr-d/DOFavoriteButton.git
git clone https://github.com/shinobicontrols/iOS8-day-by-day.git
git clone https://github.com/badoo/Chatto.git
git clone https://github.com/gontovnik/DGElasticPullToRefresh.git
git clone https://github.com/IFTTT/RazzleDazzle.git
git clone https://github.com/hyperoslo/Whisper.git
git clone https://github.com/hyperoslo/ImagePicker.git
git clone https://github.com/daltoniam/Starscream.git
git clone https://github.com/qvacua/vimr.git
git clone https://github.com/ephread/Instructions.git
git clone https://github.com/Yalantis/Persei.git
git clone https://github.com/patchthecode/JTAppleCalendar.git
git clone https://github.com/kahopoon/Pokemon-Go-Controller.git
git clone https://github.com/JadenGeller/Helium.git
git clone https://github.com/shadowsocks/ShadowsocksX-NG.git
git clone https://github.com/austinzheng/swift-2048.git
