mkdir -p TypeScript
cd TypeScript
git clone https://github.com/driftyco/ionic.git
git clone https://github.com/Microsoft/vscode.git
git clone https://github.com/angular/angular.git
git clone https://github.com/Microsoft/TypeScript.git
git clone https://github.com/vshatskyi/black-screen.git
git clone https://github.com/angular-ui/ui-router.git
git clone https://github.com/DefinitelyTyped/DefinitelyTyped.git
git clone https://github.com/NativeScript/NativeScript.git
git clone https://github.com/angular/angular-cli.git
git clone https://github.com/sahat/satellizer.git
git clone https://github.com/angular/material2.git
git clone https://github.com/cyclejs/cyclejs.git
git clone https://github.com/palantir/blueprint.git
git clone https://github.com/ReactiveX/rxjs.git
git clone https://github.com/akveo/ng2-admin.git
git clone https://github.com/tensorflow/playground.git
git clone https://github.com/BabylonJS/Babylon.js.git
git clone https://github.com/winjs/winjs.git
git clone https://github.com/mgechev/angular-seed.git
git clone https://github.com/jquery/esprima.git
git clone https://github.com/mozilla/shumway.git
git clone https://github.com/calebmer/postgraphql.git
git clone https://github.com/turbulenz/turbulenz_engine.git
git clone https://github.com/esvit/ng-table.git
git clone https://github.com/typings/typings.git
git clone https://github.com/searchkit/searchkit.git
git clone https://github.com/ceolter/ag-grid.git
git clone https://github.com/Microsoft/code-push.git
git clone https://github.com/electron-userland/electron-builder.git
git clone https://github.com/valor-software/ng2-bootstrap.git
git clone https://github.com/ng-bootstrap/ng-bootstrap.git
git clone https://github.com/Microsoft/vscode-go.git
git clone https://github.com/MicrosoftDX/Vorlonjs.git
git clone https://github.com/ngrx/store.git
git clone https://github.com/Urigo/angular-meteor.git
git clone https://github.com/space10-community/conversational-form.git
git clone https://github.com/palantir/plottable.git
git clone https://github.com/apollographql/apollo-client.git
git clone https://github.com/angular/zone.js.git
git clone https://github.com/phodal/growth.git
git clone https://github.com/angular/universal.git
git clone https://github.com/pnpm/pnpm.git
git clone https://github.com/Microsoft/TypeScriptSamples.git
git clone https://github.com/jupyterlab/jupyterlab.git
git clone https://github.com/rhysd/NyaoVim.git
git clone https://github.com/NathanWalker/angular-seed-advanced.git
git clone https://github.com/palantir/tslint.git
git clone https://github.com/angular/angularfire2.git
git clone https://github.com/typeorm/typeorm.git
git clone https://github.com/driftyco/ionic-conference-app.git
git clone https://github.com/orbitjs/orbit.git
git clone https://github.com/yortus/asyncawait.git
git clone https://github.com/ant-design/ant-design-mobile.git
git clone https://github.com/APIs-guru/graphql-voyager.git
git clone https://github.com/alm-tools/alm.git
git clone https://github.com/Microsoft/TouchDevelop.git
git clone https://github.com/basarat/typescript-book.git
git clone https://github.com/sourcelair/xterm.js.git
git clone https://github.com/VSCodeVim/Vim.git
git clone https://github.com/n3-charts/line-chart.git
git clone https://github.com/Polymer/polymer-bundler.git
git clone https://github.com/driftyco/ionic-native.git
git clone https://github.com/tessera-metrics/tessera.git
git clone https://github.com/angular/universal-starter.git
git clone https://github.com/vmware/clarity.git
git clone https://github.com/superpowers/superpowers-core.git
git clone https://github.com/DefinitelyTyped/tsd.git
git clone https://github.com/colmena/colmena-cms.git
git clone https://github.com/rangle/augury.git
git clone https://github.com/plasma-umass/doppio.git
git clone https://github.com/inversify/InversifyJS.git
git clone https://github.com/appbaseio/mirage.git
git clone https://github.com/learnapollo/learnapollo.git
git clone https://github.com/pillarjs/path-to-regexp.git
git clone https://github.com/ngx-translate/core.git
git clone https://github.com/KotlinBy/awesome-kotlin.git
git clone https://github.com/mgechev/codelyzer.git
git clone https://github.com/angular/angular2-seed.git
git clone https://github.com/tgdwyer/WebCola.git
git clone https://github.com/staltz/xstream.git
git clone https://github.com/OfficeDev/office-ui-fabric-react.git
git clone https://github.com/auth0/angular2-jwt.git
git clone https://github.com/Microsoft/vscode-react-native.git
git clone https://github.com/zhongsp/TypeScript.git
git clone https://github.com/service-mocker/service-mocker.git
git clone https://github.com/TypeStrong/atom-typescript.git
git clone https://github.com/apollographql/graphql-server.git
git clone https://github.com/alexjlockwood/ShapeShifter.git
git clone https://github.com/robertknight/webpack-bundle-size-analyzer.git
git clone https://github.com/angular/flex-layout.git
git clone https://github.com/housseindjirdeh/angular2-hn.git
git clone https://github.com/swimlane/ngx-datatable.git
git clone https://github.com/TypeStrong/ts-node.git
git clone https://github.com/furnishup/blueprint3d.git
git clone https://github.com/angular-redux/store.git
git clone https://github.com/Chatie/wechaty.git
git clone https://github.com/justindujardin/ng2-material.git
git clone https://github.com/born2net/Angular-kitchen-sink.git
git clone https://github.com/urish/angular-spinner.git
git clone https://github.com/vladotesanovic/ngSemantic.git
